### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by CelineK**
Hello,

@mir-ak and me found an error when typing the command `yarn dev`. We found a solution and added it to the CONTRIBUTING.md file. What do you think ?

Thank you !

### CODE REVIEW

**Comment by nicofrand** [comment]
Hi,

thank you very much for your contribution!

However there already is an explanation above that explains that the config.example.ini (there is one at the root) must be copied and edited:

> Copy config.example.ini to config.ini and set values for your local development environment. See "setting up a database for development" below.

But maybe you did not find the sentence clear enough?

**Comment by CelineK** [comment]
Hi, 

We tried several times with the `config.example.ini` file at the root and it didn't work. We had the following error: 
`[4] [HPM] Error occurred while trying to proxy request / api / all / from 0.0.0.0:8080 to http: // localhost: 9876 / (ECONNREFUSED) (https: // nodejs. org / api / errors.html # errors_common_system_errors).`
Oddly, we just retested from scratch and now it works with that file. We don't know why but it's good.

Thank you !

**Comment by CelineK** [comment]
I also had a question. We want to translate the app into Arabic and / or Turkish, what do you say?

**Comment by nicofrand** [comment]
This sounds really nice!

Two things though:

1. I fear our app is not ready for right-to-left languages and I guess some CSS will need to be tweaked. Would you be comfortable with that?
2. We don't use any tool like weblate for translations (yet) so you'd have to edit the JSON files directly. Is that OK?
 
Also, none of the maintainers speak arabic or turkish, so we won't be able to maintain those languages. Do you plan to maintain them in the future (when we add translation keys etc)?

**Comment by CelineK** [comment]
Sorry for the delay.

We chose these languages because we know them. But my friend tested the Arabic language and it turns out to be more difficult than we imagined. So he chose Spanish. We hope you are okay with this :)

**Comment by bnjbvr** [comment]
Hi! That also sounds great to me, thanks!

We're doing most of our developments on https://framagit.org/kresusapp/kresus, yet we can still use Github if you do strongly prefer it. Would you mind using Framagit instead?

**Comment by CelineK** [comment]
No worries, we'll be using Framagit, but are we going to continue our contribution on Github or have to re-request on Framagit?

**Comment by bnjbvr** [comment]
I am not sure what you're asking. This specific pull request could be closed, since we seem to agree that the readme already contained information regarding how to set up the database for development and how to use the dev command in general. If you think the wording isn't clear, feel free to tweak it, in this PR or a new one on Framagit :)

And for the translation bits, yes please a new PR on Framagit would be simpler for us!

**Pull request closed without merging**
